FROM eclipse-temurin:17-jre-alpine


# Verzeichnis, in das dein externes DATA-Volume gemountet wird
ENV DATA=/data
VOLUME ["/data"]

WORKDIR /app

# ggf. Pfad anpassen, falls Multi-Module:
# COPY enex-services/target/*-shaded.jar /app/app.jar
COPY java/runner/target/evernote-tagging-runner-*.jar app.jar

ENTRYPOINT ["java", "-cp", "/app/app.jar"]
